apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  namespace: default
  name: dynamicuifields
  title: Dynamic UI Fields
  description: Test out dynamic UI fields form catalog metadata
  tags:
    - dynamic
    - catalogmetadata
spec:
  owner: cassie.souza@harness.io
  type: environment
  parameters:
    - title: Project and Repo Details
      required:
        - owner
      properties:
        projectName:
            title: Input Project Name
            type: string
            description: New project to onboard   
        appID:
            title: Choose Application ID
            type: string
            description: Application ID for this service request
            ui:field: EntityFieldPicker
            ui:displayField: metadata.appID
            ui:options:
              catalogFilter:
                - kind: Component
                  spec.type: website
        jenkinsInstance:
            title: Choose a Jenkins Instance
            type: string
            description: Jenkins Instance to orchestrate the project onboarding
            ui:field: EntityFieldPicker
            ui:displayField: metadata.jenkinsInstance
            ui:options:
              catalogFilter:
                - kind: Component
                  spec.type: website
            dependencies:
              - appID
            ui:conditional:
              if: "{{ parameters.appID == '123' }} || parameters.appID == '112233' }}" 
              then:
                enum:
                  - jenkins1
                  - jenkins2
                  - jenkins3
              if: "{{ parameters.appID == '456' }}" 
              then:
                enum:
                  - jenkins4
                  - jenkins5
                  - jenkins6
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
  steps:
    - id: trigger
      name: Provisioning your Infrastructure
      action: trigger:harness-custom-pipeline
      input:
        url: https://app.harness.io/ng/account/6_vVHzo9Qeu9fXvj-AcbCQ/home/orgs/SE_Sandbox/projects/Cassie_Sandbox/pipelines/Dynamic_Form_Inputs/pipeline-studio/?storeType=INLINE
        inputset:
          appID: ${{ parameters.appID }}
        apikey: ${{ parameters.token }}
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
